_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 55
            "3":
                - 4
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
epochs:
    value: 1000
learning_rate:
    value: 0.001
pretrain_batch_size:
    value: 640
